#!/usr/bin/env node

"use strict";

var cli = require('commander');
var rek = require('rekuire');
var version = require('../package.json').version;

var nsyrc = rek('nsyrc-cli');

cli
    .version(version)
    .usage("[ link [ from <SOURCE> to <TARGET> ] | unlink | show | run ]")
    .option("link", "Set a new nsyrc link",Boolean, false)
    .option("from <path>", "source of a new link")
    .option("to <path>", "target of a new link")
    .option("unlink [id]", "remove a link")
    .option("show", "Prints the nsyrc links for the current folder",Boolean, false)
    .option("run [id]", "Run a link")
    .parse(process.argv);


if (cli.from && cli.to) {
    nsyrc.link(cli.from, cli.to);
} else if (cli.link) {
    nsyrc.link();
} else if (cli.unlink) {
    nsyrc.unlink(cli.unlink);
} else if (cli.show) {
    nsyrc.show();
} else if (cli.run) {
    nsyrc.run(cli.run);
} else {
    nsyrc.show();
}
