#!/usr/bin/env node

"use strict";

var cli = require('commander');
var rek = require('rekuire');
var version = require('../package.json').version;

var nsyrc = rek('nsyrc-cli');

cli
    .version(version)
    .option("link", "Set a new nsyrc link",Boolean, false)
    .option("unlink", "remove a link",Boolean, false)
    .option("show", "Prints the nsyrc links for the current folder",Boolean, false)
    .option("run", "Run the default nsyrc link",Boolean, false) //add optional index
    .parse(process.argv);

if (cli.link) {
    nsyrc.link();
} else if (cli.unlink) {
    nsyrc.unlink();
} else if (cli.show) {
    nsyrc.show();
} else if (cli.run) {
    nsyrc.run();
} else {
    nsyrc.show();
}
