#!/usr/bin/env node

"use strict";

var cli = require('commander');
var clc = require('cli-color');
var rek = require('rekuire');
var version = rek('package.json').version;

var tcmount_cli = rek('tcmount-cli');

cli
    .version(version)
    .usage("[<file> | <file> <mountpoint> | <mountpoint> | -m [id] ]")
    .option("-l, --link", "create a link from <file> to <mountpoint>")
    .option("-m, --mount", "mount by file, mountpoint, or link id")
    .option("-u, --unmount", "unmount by file, mountpoint, or link id")
    .option("-t, --trash <id>", "delete a link by id", parseInt)
    .parse(process.argv);


var targets = process.argv.slice(2).filter(function(v) { return v.indexOf("-") != 0; });

if (targets.length > 2) {
    return console.log(clc.red("Too many arguments!! Besides flags, there can't be more than two."));
}

if (cli.link) {
    tcmount_cli.createLink(targets);
} else if (cli.trash) {
    tcmount_cli.trash(cli.trash);
} else if (cli.unmount) {
    tcmount_cli.unmount(targets);
} else if (cli.mount || targets.length > 0) {
    tcmount_cli.mount(targets);
} else {
    tcmount_cli.show();
}
